<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <title><?php echo TITLE . " - " . $view_pagina; ?></title>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
        <link rel="stylesheet" type="text/css" href="/web-files/bootstrap/css/bootstrap.css">
        <link rel="stylesheet" type="text/css" href="/web-files/font-awesome-4.1.0/css/font-awesome.css">
    </head>
    <body>

        <div style=" border: 1px solid black; padding: 5px">
            <table align="center" style="width: 100%">
                <tr>
                    <td style="">
                        <img src="/web-files/img/parceria250.png" border="0" alt="Parceria Consult" title="Parceria Consult" width="100px"/>
                    </td>
                    <td align="center">
                        <div>ACORDO DE COOPERAÇÃO E <br/> TERMO DE COMPROMISSO DE ESTÁGIO</div>
                    </td>
                </tr>
            </table>
        </div>
        <?php
        $dta_inicio = "";
        $dta_fim = "";
        $dta_fim_atual = date('d') . "/" . date('m') . "/" . date('Y');
        $stg_cargo = "";
        $stg_curso = "";

        if ($view_dados_complementares) {
            foreach ($view_dados_complementares as $obj) {
                $stg_curso = $obj->CURSO;
                $dta_inicio = $obj->DTA_INICIO;
                $dta_fim = $obj->DTA_FIM;
                $stg_cargo = $obj->CARGO;
                $bolsa_valor_extenso = $obj->BOLSA_VALOR_EXTENSO;
                $bolsa_valor = $obj->BOLSA_VALOR;
                $carga_horaria = $obj->CARGA_HORARIA;
                ($obj->CARGA_HORARIA_OBS == "") ? $obj->CARGA_HORARIA_OBS : $carga_horaria_obs = " ({$obj->CARGA_HORARIA_OBS})";
            }
        }

        $di = explode("/", $dta_inicio);

        switch ($di[1]) {
            case "01": $di[1] = "Janeiro";
                break;
            case "02": $di[1] = "Fevereiro";
                break;
            case "03": $di[1] = "Março";
                break;
            case "04": $di[1] = "Abriu";
                break;
            case "05": $di[1] = "Maio";
                break;
            case "06": $di[1] = "Junho";
                break;
            case "07": $di[1] = "Julho";
                break;
            case "08": $di[1] = "Agosto";
                break;
            case "09": $di[1] = "Setembro";
                break;
            case "10": $di[1] = "Outubro";
                break;
            case "11": $di[1] = "Novembro";
                break;
            case "12": $di[1] = "Dezembro";
                break;
        }

        $df = explode("/", $dta_fim);

        switch ($df[1]) {
            case "01": $df[1] = "Janeiro";
                break;
            case "02": $df[1] = "Fevereiro";
                break;
            case "03": $df[1] = "Março";
                break;
            case "04": $df[1] = "Abriu";
                break;
            case "05": $df[1] = "Maio";
                break;
            case "06": $df[1] = "Junho";
                break;
            case "07": $df[1] = "Julho";
                break;
            case "08": $df[1] = "Agosto";
                break;
            case "09": $df[1] = "Setembro";
                break;
            case "10": $df[1] = "Outubro";
                break;
            case "11": $df[1] = "Novembro";
                break;
            case "12": $df[1] = "Dezembro";
                break;
        }
        ?>


        <p>
            - Instrumento Jurídico de que trata a Lei nº 11.788 de 25/09/2008.<br/>
            Aos <?php echo "{$di[0]} {$di[1]} de {$di[2]} ao dia {$df[0]} do mês de {$df[1]} de {$df[2]}"; ?> na cidade do Rio de Janeiro TCE este ato as partes a seguir nomeadas.
        </p>

        <?php
        if ($view_dados_complementares) {
            foreach ($view_dados_complementares as $obj) {
                $stg_curso = $obj->CURSO;
                $dta_inicio = $obj->DTA_INICIO;
                $dta_fim = $obj->DTA_FIM;
                $stg_cargo = $obj->CARGO;
                $stg_ctps = $obj->CTPS;
                $stg_serie = $obj->SERIE;
                $nome_instituicao = $obj->INTITUICAO_ENSINO;
                $representante_intituicao = $obj->REPRESENTANTE_INTITUICAO;
                $cargo_instituicao = $obj->CARGO_REPRESENTANTE;
                $stg_ctps = $obj->CTPS;
                $stg_serie = $obj->SERIE;
            }
        }

        if ($view_INST_COMPLEMENTO != "") {
            $complemento_inst = "{$view_INST_COMPLEMENTO}<br/>";
        }
        
        ?>

        <div style=" border: 1px solid black; padding: 5px"> 
            <h4 style="text-align: center;">INSTITUIÇÃO DE ENSINO</h4>
            <table align="center" style="width: 100%">
                <tr>
                    <td style="font-size: 10px;" valign="top" align="right"><b>Razão Social:</b>  </td>
                    <td style="font-size: 12px;" valign="top"><?php echo $nome_instituicao; ?></td>
                </tr>
                <tr>
                    <td style="font-size: 10px;" valign="top" align="right"><b>Endereço:</b>  </td>
                    <td style="font-size: 12px;" valign="top"><?php echo "{$view_INST_LOGRADOURO} , {$view_INST_NUMERO}- {$view_INST_BAIRRO}- {$complemento_inst} - {$view_INST_CIDADE}/{$view_INST_UF}, <span style='font-size: 10px;'><b>Cep:</b></span> {$view_INST_CEP}"; ?></td>
                </tr>
                <tr>
                    <td style="font-size: 10px;" valign="top" align="right"><b>Representada por:</b> </td>
                    <td style="font-size: 12px;" valign="top"><?php echo $representante_intituicao; ?>, <span style="font-size: 10px;"><b>Cargo:</b></span> <?php echo $cargo_instituicao; ?></td>
                </tr>
            </table>
        </div>

        <br/>

        <div style=" border: 1px solid black; padding: 5px"> 
            <h4 style="text-align: center;">UNIDADE CONCEDENTE</h4>
            <table align="center" style="width: 100%">
                <tr>
                    <td style="font-size: 10px;" valign="top" align="right"><b>Razão Social:</b> </td>
                    <td style="font-size: 12px;" valign="top"><?php echo $view_estagiario_empresa->EMP_NOME; ?></td>
                </tr>

<?php
if ($view_EMP_COMPLEMENTO != "") {
    $complemento = "{$view_EMP_COMPLEMENTO}<br/>";
}
?>
                <tr>
                    <td style="font-size: 10px;" valign="top" align="right"><b>Endereço:</b> </td>
                    <td style="font-size: 12px;" valign="top"><?php echo "{$view_EMP_LOGRADOURO} , {$view_EMP_NUMERO}- {$view_EMP_BAIRRO}- {$complemento} - {$view_EMP_CIDADE}/{$view_EMP_UF}, <span style='font-size: 10px;'><b>Cep:</b></span> {$view_EMP_CEP}"; ?></td>
                </tr>
                <tr>
                    <td style="font-size: 10px;" valign="top" align="right"><b>CNPJ/MF:</b> </td>
                    <td style="font-size: 12px;" valign="top"><?php echo $view_estagiario_empresa->EMP_CNPJ; ?></td>
                </tr>
                <tr>
                    <td style="font-size: 10px;" valign="top" align="right"><b>Supervisor(a):</b> </td>
                    <td style="font-size: 12px;" valign="top"><?php echo $view_estagiario_empresa->ADM_NOME; ?>, <span style="font-size: 10px;"><b>Cargo:</b></span> <?php echo $view_estagiario_empresa->ADM_CARGO; ?></td>
                </tr>
            </table>
        </div> 

        <br/>

        <p style="text-align: justify; font-size: 12px;">Celebram entre si <b>ACORDO DE COOPERAÇÃO</b>, convencionando as cláusulas e condições seguintes:</p>
        <p style="text-align: justify; font-size: 12px;"><b>Cláusula 1ª</b> - O <b>ACORDO DE COOPERAÇÃO</b> tem por objetivo formalizar as condições básicas para a realização de
            <a href="../../controllers/adminController.php"></a>

            <b>ESTÁGIO DE ESTUDANTES</b> da <b>INSTITUIÇÃO DE ENSINO</b> junto à <b>UNIDADE CONCEDENTE</b>, o qual, obrigatório ou não, deve ser

            de interesse curricular e pedagogicamente útil, entendido o <b>ESTÁGIO</b> como uma <b>ESTRATÉGIA DE PROFISSIONALIZAÇÃO</b> que

            integra o <b>PROCESSO DE ENSINO APRENDIZAGEM</b>.</p>

        <p style="text-align: justify; font-size: 12px;"><b>Cláusula 2ª</b> - Em decorrência do presente Acordo, celebra-se um <b>TERMO DE COMPROMISSO DE ESTÁGIO - TCE</b>, entre o

            Estudante e a <b>UNIDADE CONCEDENTE</b>, com interveniência da <b>INSTITUIÇÃO DE ENSINO</b>, nos termos dos artigos 2º e 3º da

            Lei 11788/08.</p>

        <p style="text-align: justify; font-size: 12px;"><b>Cláusula 3ª</b> - As condições básicas para a realização de <b>ESTÁGIO</b> estão explicitadas no <b>TERMO DE COMPROMISSO DE

                ESTÁGIO - TCE</b>, que se vincula ao presente acordo.</p>

        <p style="text-align: justify; font-size: 12px;">A <b>UNIDADE CONCEDENTE</b>, com interveniência e assinatura da <b>INSTITUIÇÃO DE ENSINO</b>, e, de outro lado, o</p>

<?php
if ($view_STG_COMPLEMENTO != "") {
    $complemento_stg = "{$view_STG_COMPLEMENTO}<br/>";
}
?>


        <div style=" border: 1px solid black; padding: 5px"> 
            <h4 style="text-align: center;">ESTAGIARIO</h4>
            <table align="center" style="width: 100%">
                <tr>
                    <td style="font-size: 10px;" valign="top" align="right"><b>Nome:</b> </td>
                    <td style="font-size: 12px;" valign="top"><?php echo $view_estagiario_empresa->STG_NOME; ?></td>
                </tr>
                <tr>
                    <td style="font-size: 10px;" valign="top" align="right"><b>Endereço:</b> </td>
                    <td style="font-size: 12px;" valign="top"><?php echo "{$view_STG_LOGRADOURO} , {$view_STG_NUMERO}- {$view_STG_BAIRRO}- {$complemento_stg} - {$view_STG_CIDADE}/{$view_STG_UF}, <span style='font-size: 10px;'><b>Cep:</b></span> {$view_STG_CEP}"; ?></td>
                </tr>
                <tr>
                    <td style="font-size: 10px;" valign="top" align="right"><b>Curso:</b> </td>
                    <td style="font-size: 12px;" valign="top">Ciências Econômicas</td>
                </tr>
                <tr>
                    <td style="font-size: 10px;" valign="top" align="right"><b>CTPS:</b> </td>
                    <td style="font-size: 12px;" valign="top"><?php echo $stg_ctps; ?> <span style="font-size: 10px;"><b>Série:</b></span> <?php echo $stg_serie; ?></td>
                </tr>
            </table>
        </div> 

        <br/>





        <p style="text-align: justify; font-size: 12px;">Celebram entre si este <b>TERMO DE COMPROMISSO DE ESTÁGIO - TCE</b>, convencionando as cláusulas e condições seguintes:</p>

        <p style="text-align: justify; font-size: 12px;"><b>Cláusula 4ª</b> - O <b>TERMO DE COMPROMISSO DE ESTÁGIO - TCE</b>, que decorre do <b>ACORDO DE COOPERAÇÃO</b>, tem por finalidade

            particularizar a relação jurídica especial existente entre o <b>ESTAGIÁRIO</b> e a <b>UNIDADE DE CONCEDENTE</b>, caracterizando

            a não vinculação empregatícia.</p>


        <p style="text-align: justify; font-size: 12px;"><b>Cláusula 5ª</b> - Na vigência do presente Termo, o <b>ESTAGIÁRIO</b> estará incluído na cobertura do <b>SEGURO CONTRA ACIDENTES

                PESSOAIS</b>, proporcionado pela <b>APÓLICE</b> da <b>Seguradora Porto Seguro numero 211241-0/208287-2</b>.</p>

        <p style="text-align: justify; font-size: 12px;">Sob a responsabilidade da <b>PARCERIA</b>, conforme certificado Individual de Seguro fornecido ao <b>ESTAGIÁRIO</b>.</p>

        <p style="text-align: justify; font-size: 12px;"><b>Cláusula 6ª</b> - Ficam compromissadas entre as partes as seguintes condições básicas para a realização do <b>ESTÁGIO</b>:</p>

        <p style="text-align: justify; font-size: 12px;"><b>a)</b> este <b>TERMO DE COMPROMISSO DE ESTÁGIO - TCE</b> terá vigência de <?php echo $dta_inicio; ?> a <?php echo $dta_fim; ?> podendo ser Denunciado a

            qualquer tempo unilateralmente, mediante comunicação escrita ou ser prorrogado através da emissão de um <b>TERMO

                ADITIVO</b>.</p>


        <p style="text-align: justify; font-size: 12px;"><b>b)</b> É assegurado ao estagiário - Lei 11788/08 artigo 13 - sempre que o estagio tenha duração igual ou superior a

            um ano, período de recesso de 30 dias a ser gozado preferencialmente durante suas férias escolares.

            Esse recesso deverá ser sempre remunerado se o estagiário receber bolsa auxilio ou outra forma de contraprestação

            em acordo com o parágrafo 1o do artigo 2º da Lei 11788/08.</p>


        <p style="text-align: justify; font-size: 12px;">Aos contratos com duração inferior a um ano o recesso será concedido conforme previsto no parágrafo 2º do artigo

            13 da Lei 11788/08.</p>


        <p style="text-align: justify; font-size: 12px;"><b>c)</b> Se a instituição de ensino adotar verificações de aprendizagem periódicas ou finais, nos períodos de avaliação

            a carga horária do estágio será reduzida pelo menos à metade, segundo estipulado no termo de compromisso, para

            garantir o bom desempenho do estudante. As atividades de <b>ESTÁGIO</b> a serem cumpridas pelo <b>ESTAGIÁRIO</b> serão

            desenvolvidas na carga horária de <b><?php echo $carga_horaria.$carga_horaria_obs; ?></b> horas diárias, no horário de

            <b>13:00</b> as <b>19:00</b> com 1:00 hora de intervalo, totalizando as <b>30(Trinta)</b> horas semanais</p>

        <p style="text-align: justify; font-size: 12px;"><b>d)</b> as atividades principais a serem desenvolvidas pelo estagiário na <b>FUNDAÇÃO DE ASSISTENCIA E PREVIDENCIA SOC</b> em

            caráter complementar, compatíveis com o Contexto Básico da Profissão ao qual o curso se refere são:</p>


        <p style="text-align: justify; font-size: 12px;">
            Atualização de informações e relatórios gerencias; Manipulação de sistemas de análise de performance de 

            investimento da Fundação(Blomberg,Mitra); Manipulação de planilhas de acompanhamento dos investimentos 

            realizados pela Fundação; Atualização diária de banco do dados com informações diárias do mercado; etc...

        </p>


        <p style="text-align: justify; font-size: 12px;"><b>e)</b> durante a realização do estágio, o Estudante receberá uma bolsa auxílio mensal, cujo valor inicial será de:

            R$ <?php echo $bolsa_valor." ".$bolsa_valor_extenso; ?> por Mês , mais auxilio transporte.

        </p>


        <p style="text-align: justify; font-size: 12px;">
            <b>f)</b> O valor da Bolsa-Auxílio poderá variar de acordo com a freqüência ao estágio e está sujeita a Retenção no

            Imposto de Renda, conforme tabela de incidência fixada pelo Ministério da Fazenda que estiver em vigor.

        </p>


        <p style="text-align: justify; font-size: 12px;"><b>g)</b> O <b>PAGAMENTO</b> da Bolsa-Auxílio acima será efetuado diretamente pela Unidade Concedente de Estágio.</p>

        <p style="text-align: justify; font-size: 12px;"><b>Cláusula 7ª</b> - No desenvolvimento do <b><b>ESTÁGIO</b> ora compromissado, caberá a <b>UNIDADE CONCEDENTE</b>:</p>

        <p style="text-align: justify; font-size: 12px;"><b>a)</b> Proporcionar ao <b>ESTAGIÁRIO</b>, atividades de aprendizagem social, profissional e cultural, compatíveis com o

            Contexto Básico da Profissão, ao qual seu curso se refere ;</p>


        <p style="text-align: justify; font-size: 12px;"><b>b)</b> Proporcionar à <b>INSTITUIÇÃO DE ENSINO e/ou à PARCERIA</b>, sempre que necessário, subsídios que possibilitem o

            acompanhamento, a supervisão e avaliação do <b>ESTÁGIO</b>.</p>

        <p style="text-align: justify; font-size: 12px;"><b>a)</b> cumprir, com todo empenho e interesse, toda programação estabelecida para seu <b>ESTÁGIO</b>;</p>

        <p style="text-align: justify; font-size: 12px;"><b>b)</b> Observar e obedecer as normas internas da <b>UNIDADE CONCEDENTE</b>;</p>



        <p style="text-align: justify; font-size: 12px;">c) elaborar e entregar à <b>PARCERIA</b>, para posterior análise da <b></b>, relatório(s) sobre seu

            <b>ESTÁGIO</b>, na forma, prazo e padrões estabelecidos.</p>


        <p style="text-align: justify; font-size: 12px;"><b>Cláusula 9a</b> - Constituem motivos para a <b>INTERRUPÇÃO AUTOMÁTICA DA VIGÊNCIA</b> do presente <b>TERMO DE COMPROMISSO DE

                ESTÁGIO:<b></p>



                    <p>I - a conclusão ou abandono do curso e o trancamento da matrícula;</p>
                    <p>II - o não cumprimento do convencionado neste <b>TERMO DE COMPROMISSO DE ESTÁGIO</b>, bem como, do <b>ACORDO DE COOPERAÇÃO

                            do qual decorre;</p>
                    <p>III - desistência do estágio ou rescisão do presente Termo.</p>

                    <p><b>Cláusula 10ª</a></b> - <b>A INSTITUIÇÃO DE ENSINO</b>, a <b>UNIDADE CONCEDENTE</b> e o <b>ESTAGIÁRIO</b>, signatários deste Termo, de comum

                            acordo e para os efeitos do art 5º. da Lei 11788/08 elegem, como seu representante e órgão de apoio, a

                            <b>PARCERIA</b>, com sede a <b>R. URUGUAIANA nº 0010 - SALAS 2204 A 2207 - CENTRO - RIO DE JANEIRO/RJ</b>, Cep: <b>20050-090</b> sob o CGC <b>01.194.833/0001-01</b>, e Inscrição Estadual <b>78297123</b>, no desempenho de um de seus papéis,

                            isto é, o de <b>AGENTE DE INTEGRAÇÃO</b>, ao qual delegam os procedimentos subsidiários, de caráter legal,  técnico,

                            burocrático e administrativo, necessários à realização do <b>ESTÁGIO</b> e a quem a comunicarão a interrupção, a

                            conclusão ou as eventuais modificações do convencionado no presente Termo.</p>

                    <p><b>Parágrafo Único:</b> Se durante a vigência desse Acordo de Cooperação e Termo de Compromisso de Estágio, a PARCERIA,

                        EM SUA CONDIÇÃO DE Agente de Integração, cuja legitimidade, atribuições e responsabilidades são do conhecimento

                        das partes contratantes, identificar violação dos compromissos assumidos por quaisquer das partes, cessarão suas

                        responsabilidades legais, técnicas e administrativas, devendo o mesmo cientificar, por escrito, todas as partes

                        envolvidas.</p>

                    <p><b>E, por estarem de inteiro e comum acordo com as condições e dizeres do ACORDO DE COOPERAÇÃO e do decorrente

                            TERMO DE COMPROMISSO DE ESTÁGIO - TCE, as partes assinam-nos em 04 (quatro) vias de igual teor.</b></p>

                    <p>

                    <table style="width: 100%">
                        <tr>
                            <td align="center">____________________________________</td>
                            <td align="center">____________________________________</td>
                        </tr>
                        <tr>
                            <td align="center">INSTITUIÇÃO DE ENSINO</td>
                            <td align="center">ESTAGIÁRIO(A)</td>
                        </tr>
                        <tr>
                            <td align="center"><br/></td>
                            <td align="center"><br/></td>
                        </tr>
                        <tr>
                            <td align="center"><br/></td>
                            <td align="center"><br/></td>
                        </tr>
                        <tr>
                            <td align="center">____________________________________</td>
                            <td align="center">____________________________________</td>
                        </tr>
                        <tr>
                            <td align="center">UNIDADE CONCEDENTE</td>
                            <td align="center">AGENTE DE INTEGRAÇÃO</td>
                        </tr>
                        <tr>
                            <td align="center"><br/></td>
                            <td align="center"><br/></td>
                        </tr>
                    </table>

                    </p>


                    </body>
                    </html>
