<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <title><?php echo TITLE . " - " . $view_pagina; ?></title>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
        <link rel="stylesheet" type="text/css" href="/web-files/bootstrap/css/bootstrap.css">
        <link rel="stylesheet" type="text/css" href="/web-files/font-awesome-4.1.0/css/font-awesome.css">
    </head>
    <body>

        <div style=" border: 1px solid black; padding: 5px">
            <table align="center" style="width: 100%">
                <tr>
                    <td style="">
                        <img src="/web-files/img/parceria250.png" border="0" alt="Parceria Consult" title="Parceria Consult" width="100px"/>
                    </td>
                    <td align="center">
                        <div>PARCERIA CONSULTORIA EMPRESARIAL LTDA</div>
                        <div>Empresa: <?php echo $view_empresa->NOME_RAZAO_SOCIAL; ?></div>
                        <div>CNPJ: <?php echo $view_empresa->CNPJ; ?></div>
                    </td>
                </tr>
            </table>
        </div>

        <h2 style="text-align: center;"><span class="label label-default">NOMES DE ESTAGIÁRIOS</span></h2>

        <div class='panel panel-default'>
            <table class='table'>
                <tbody>
                    
                        <?php if($view_nomes_estagiarios) { ?>
                            <?php 
                                $i=1;
                                foreach ($view_nomes_estagiarios as $nome) {
                                    (strlen((string) $i) == 1) ? $n = "0{$i}" : $n = $i;
                                    echo "<tr><td>{$n} - {$nome->NOME}</td></tr>";
                                    $i++;
                                }
                            ?>
                            
                        <?php } else { ?>
                            <tr><td>* Nenhum estagiário ligado a esta empresa! </td></tr>
                        <?php } ?>    
                    
                </tbody>
            </table>
        </div>


    </body>
</html>
