<pre>
    <p style="font-size: 14px;">
        <?php
            echo "<h1>Empresa</h1>";
            echo "<p><b>Razão Social: </b>" . $view_nome_razao_social . "</p>";
            echo "<p><b>CNPJ: </b>" . $view_cnpj . "</p>";
            echo "<p><b>E-mail: </b>" . $view_email . "</p>";
            echo "<p><b>Site: </b>" . $view_site . "</p>";
            echo "<h1>Acompanhamento do administrador</h1>";
            echo "<p><b>CPF: </b>" . $view_cpf . "</p>";
        ?>
    </p>
</pre>