<pre>
    <p style="font-size: 14px;">
        <?php
            echo "<h1>Estagiário</h1>";
            echo "<p><b>Nome: </b>" . $view_estagiario_empresa->STG_NOME . "</p>";
            echo "<p><b>CPF: </b>" . $view_estagiario_empresa->STG_CPF . "</p>";
            
            echo "<h1>Responsável</h1>";
            echo "<p><b>Nome: </b>" . $view_estagiario_empresa->ADM_NOME . "</p>";
            echo "<p><b>CPF: </b>" . $view_estagiario_empresa->ADM_CPF . "</p>";
            
            echo "<h1>Empresa</h1>";
            echo "<p><b>Nome: </b>" . $view_estagiario_empresa->EMP_NOME . "</p>";
            echo "<p><b>CNPJ: </b>" . $view_estagiario_empresa->EMP_CNPJ . "</p>";
            
        ?>
    </p>
</pre>
