</div>

</div>

</div> 

<footer class="bs-docs-footer" role="contentinfo" style="padding-top: 40px; padding-bottom: 40px; margin-top: 100px; color: #777; text-align: center; border-top: 1px solid #e5e5e5">
    <div class="row">
            <div class="col col-sm-6">
                &copy; 2014 - Todos os direitos Parceriaconsult
            </div>    
            <div class="col col-sm-6">
                <span>Desenvolvido por </span><a href="http://www.designlab.com.br/"><img src="/web-files/img/designlab_footer.jpg" alt="DesignLab" title="DesignLab" border="0" width="8%" style="position: relative; bottom: 2px;"/></a>
            </div>
        </div>
</footer>
<script type="text/javascript" language="javascript" src="/web-files/js/jquery-2.1.1.min.js"></script>
<script type="text/javascript" language="javascript" src="/web-files/js/html5.js"></script>
<script type="text/javascript" language="javascript" src="/web-files/bootstrap/js/bootstrap.js"></script>
<script type="text/javascript" language="javascript" src="/web-files/js/funcoes.js"></script>
<script type="text/javascript" language="javascript" src="/web-files/js/default.js"></script>

<script type="text/javascript" src="/web-files/js/jquery.uploadfile.js"></script>
<link rel="stylesheet" href="/web-files/css/uploadfile.css" type="text/css" media="screen" />

</body>
</html>






