<?php require_once 'header.phtml'; ?>        


<form method="post" class="form" >

    <ol class="breadcrumb">
        <li>Empresas e Entidades</li>
        <li><a href="/<?php echo $view_language; ?>/admin/empresas-entidades-lista-estagiarios/">Lista de Estagiarios Empresas / Entidades</a></li>
        <!--<li><a href="/<?php echo $view_language; ?>/admin/lista-avaliar-estagiario-empresa-entidade/<?php echo $view_codestagiario; ?>/<?php echo $view_codempresa; ?>">Lista de Avaliações</a></li>-->
        <li><a href="/<?php echo $view_language; ?>/admin/lista-dados-complementares-estagiario-empresa-entidade/<?php echo $view_codestagiario; ?>/<?php echo $view_codempresa; ?>">Lista de Dados Complementares do Estágio</a></li>
        <li>Questionário do Estagiário</li>
    </ol>


    <h2><span class="label label-default">Questionário do Estagiário</span></h2>
    <br/>




    <div class="panel panel-info">
        <div class="panel-heading"><h3 style="text-align: center;">1- DADOS DE IDENTIFICAÇÃO</h3></div>
        <table class='table' align="center" style="width: 100%">
            <thead>
            <th>Empresa</th>
            <th>Endereço ou local da Empresa</th>
            </thead>
            <tr>
                <td valign="top"><?php echo $view_estagiario_empresa->EMP_NOME; ?></td>
                <td valign="top">

                    <?php
                    echo "{$view_EMP_LOGRADOURO}, {$view_EMP_NUMERO}<br/>";
                    echo "{$view_EMP_BAIRRO}, {$view_EMP_CEP}<br/>";
                    if ($view_EMP_COMPLEMENTO != "") {
                        echo "{$view_EMP_COMPLEMENTO}<br/>";
                    }
                    echo "{$view_EMP_CIDADE}/{$view_EMP_UF}<br/>";
                    ?>

                </td>
            </tr>
            <thead>
            <th><br/>Supervisor do Estágio e Cargo</th>
            <th><br/>Telefone ou Email</th>
            </thead>
            <tr>
                <td valign="top"><?php echo "{$view_estagiario_empresa->ADM_NOME}<br/><b style='font-size: 9px'>{$view_estagiario_empresa->ADM_CARGO}</b>"; ?></td>
                <td valign="top">
                    <?php
                    echo $view_estagiario_empresa->ADM_EMAIL;

                    if ($view_telefones_supervisor) {
                        echo "<br/>";
                        foreach ($view_telefones_supervisor as $obj) {
                            echo "({$obj->DDD}) {$obj->TELEFONE}<br/>";
                        }
                    }
                    ?>
                </td>
            </tr>
            <thead>
            <th><br/>Nome do Estagiário e Cargo</th>
            <th><br/>Curso</th>
            <?php
            $dta_inicio = "";
            $dta_fim = "";
            $dta_fim_atual = date('d') . "/" . date('m') . "/" . date('Y');
            $stg_cargo = "";
            $stg_curso = "";

            if ($view_dados_complementares) {
                foreach ($view_dados_complementares as $obj) {
                    $stg_curso = $obj->CURSO;
                    $dta_inicio = $obj->DTA_INICIO;
                    $dta_fim = $obj->DTA_FIM;
                    $stg_cargo = $obj->CARGO;
                }
            }
            ?>
            </thead>
            <tr>
                <td valign="top"><?php echo "{$view_estagiario_empresa->STG_NOME}<br/><b style='font-size: 9px'>{$stg_cargo}</b>"; ?></td>
                <td valign="top"><?php echo $stg_curso; ?></td>
            </tr>
            <thead>
            <th><br/>Data de Entrada</th>
            <th><br/>Data de Saida</th>
            </thead>
            <tr>
                <td valign="top"><b><?php echo $dta_inicio; ?></b></td>
                <td valign="top"><b><?php echo $dta_fim_atual; ?></b></td>
            </tr>
        </table>
    </div>

    <div class="panel panel-info">
        <div class="panel-heading"><h3 style="text-align: center;">2- QUESTIONÁRIO</h3></div>
    </div>     

    <div class="form-group"> 

        <div class="panel panel-default">
            <div class="panel-heading">
                <label><strong>1) Você já recebeu a cópia do Termo de Compromisso de Estágio - TCE ?</strong></label>
                <br/>
                <?php
                
                    if(isset($view_questionario_estagiario->COPIA_TERMO)){
                        switch ($view_questionario_estagiario->COPIA_TERMO) {
                            case 1: $radio1 = "checked='true'"; break;
                            case 0: $radio0 = "checked='true'"; break;
                            default: $radio1 = "checked='true'"; break;
                        }
                    } else {
                        $radio1 = "checked='true'";
                    }
                    
                ?>
                
                <input type="radio" name="COPIA_TERMO" value="1" <?php echo $radio1; ?>> Sim 
                <input type="radio" name="COPIA_TERMO" value="0" <?php echo $radio0; ?>> Não
                <br/>
                <strong>Outras informações:</strong>
            </div>
            <div class="panel-body">
                <textarea class="form-control" id="COPIA_TERMO_DESC" name="COPIA_TERMO_DESC"> <?php echo $view_questionario_estagiario->COPIA_TERMO_DESC; ?> </textarea>
            </div>
        </div>


        <div class="panel panel-default">
            <div class="panel-heading">
                <label><strong>2) Você tem recebido o pagamento de sua Bolsa-Auxílio na data estabelecida pela Parceria ?</strong></label>
                <br/>
                <?php
                
                    unset($radio1);
                    unset($radio0);
                    
                    if(isset($view_questionario_estagiario->TEM_RECEBIDO)){
                        switch ($view_questionario_estagiario->TEM_RECEBIDO) {
                            case 1: $radio1 = "checked='true'"; break;
                            case 0: $radio0 = "checked='true'"; break;
                            default: $radio1 = "checked='true'"; break;
                        }
                    } else {
                        $radio1 = "checked='true'";
                    }
                    
                ?>
                <input type="radio" name="TEM_RECEBIDO" value="1" <?php echo $radio1; ?>> Sim 
                <input type="radio" name="TEM_RECEBIDO" value="0" <?php echo $radio0; ?>> Não
                <br/>
                <strong>Se não qual o motivo?</strong>
            </div>
            <div class="panel-body">
                <textarea class="form-control" id="TEM_RECEBIDO_DESC" name="TEM_RECEBIDO_DESC"> <?php echo $view_questionario_estagiario->TEM_RECEBIDO_DESC; ?> </textarea>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">
                <label><strong>3) O horário estabelecido pela empresa para seu Estágio está interferindo em seus estudos ?</strong></label>
                <br/>
                <?php
                
                    unset($radio1);
                    unset($radio0);
                    
                    if(isset($view_questionario_estagiario->HORARIO_INTERFERINDO)){
                        switch ($view_questionario_estagiario->HORARIO_INTERFERINDO) {
                            case 1: $radio1 = "checked='true'"; break;
                            case 0: $radio0 = "checked='true'"; break;
                            default: $radio1 = "checked='true'"; break;
                        }
                    } else {
                        $radio1 = "checked='true'";
                    }
                    
                ?>
                <input type="radio" name="HORARIO_INTERFERINDO" value="1" <?php echo $radio1; ?>> Sim 
                <input type="radio" name="HORARIO_INTERFERINDO" value="0" <?php echo $radio0; ?>> Não
                <br/>
                <strong>Se sim por que?</strong>
            </div>
            <div class="panel-body">
                <textarea class="form-control" id="HORARIO_INTERFERINDO_DESC" name="HORARIO_INTERFERINDO_DESC"> <?php echo $view_questionario_estagiario->HORARIO_INTERFERINDO_DESC; ?> </textarea>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">
                <label><strong>4) Descreva resumidamente as atividades que você desenvolve em seu estágio.</strong></label>
            </div>
            <div class="panel-body">
                <textarea class="form-control" id="ATIVIDADES_DESC" name="ATIVIDADES_DESC"> <?php echo $view_questionario_estagiario->ATIVIDADES_DESC; ?> </textarea>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">
                <label><strong>5) Você está encontrando dificuldades para desenvolver as suas atividades ?</strong></label>
                <br/>
                <?php
                
                    unset($radio1);
                    unset($radio0);
                    
                    if(isset($view_questionario_estagiario->ENCONTRANDO_DIFICULDADE)){
                        switch ($view_questionario_estagiario->ENCONTRANDO_DIFICULDADE) {
                            case 1: $radio1 = "checked='true'"; break;
                            case 0: $radio0 = "checked='true'"; break;
                            default: $radio1 = "checked='true'"; break;
                        }
                    } else {
                        $radio1 = "checked='true'";
                    }
                    
                ?>
                <input type="radio" name="ENCONTRANDO_DIFICULDADE" value="1" <?php echo $radio1; ?>> Sim 
                <input type="radio" name="ENCONTRANDO_DIFICULDADE" value="0" <?php echo $radio0; ?>> Não
                <br/>
                <strong>Se sim por que?</strong>
            </div>
            <div class="panel-body">
                <textarea class="form-control" id="ENCONTRANDO_DIFICULDADE_DESC" name="ENCONTRANDO_DIFICULDADE_DESC"> <?php echo $view_questionario_estagiario->ENCONTRANDO_DIFICULDADE_DESC; ?> </textarea>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">
                <label><strong>6) As atividades desenvolvidas estão pedagógicamente relacionada com seu curso ?</strong></label>
                <br/>
                <?php
                
                    unset($radio1);
                    unset($radio0);
                    
                    if(isset($view_questionario_estagiario->RELACIONADA_CURSO)){
                        switch ($view_questionario_estagiario->RELACIONADA_CURSO) {
                            case 1: $radio1 = "checked='true'"; break;
                            case 0: $radio0 = "checked='true'"; break;
                            default: $radio1 = "checked='true'"; break;
                        }
                    } else {
                        $radio1 = "checked='true'";
                    }
                    
                ?>
                <input type="radio" name="RELACIONADA_CURSO" value="1" <?php echo $radio1; ?>> Sim 
                <input type="radio" name="RELACIONADA_CURSO" value="0" <?php echo $radio0; ?>> Não
                <br/>
                <strong>Se não por que?</strong>
            </div>
            <div class="panel-body">
                <textarea class="form-control" id="RELACIONADA_CURSO_DESC" name="RELACIONADA_CURSO_DESC"> <?php echo $view_questionario_estagiario->RELACIONADA_CURSO_DESC; ?> </textarea>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">
                <label><strong>7) Você está obtendo acompanhamento nas suas atividades ?</strong></label>
                <br/>
                <?php
                
                    unset($radio1);
                    unset($radio0);
                    
                    if(isset($view_questionario_estagiario->ACOMPANHAMENTO_ATIVIDADES)){
                        switch ($view_questionario_estagiario->ACOMPANHAMENTO_ATIVIDADES) {
                            case 1: $radio1 = "checked='true'"; break;
                            case 0: $radio0 = "checked='true'"; break;
                            default: $radio1 = "checked='true'"; break;
                        }
                    } else {
                        $radio1 = "checked='true'";
                    }
                    
                ?>
                <input type="radio" name="ACOMPANHAMENTO_ATIVIDADES" value="1" <?php echo $radio1; ?>> Sim 
                <input type="radio" name="ACOMPANHAMENTO_ATIVIDADES" value="0" <?php echo $radio0; ?>> Não
                <br/>
                <strong>Outras informações:</strong>
            </div>
            <div class="panel-body">
                <textarea class="form-control" id="ACOMPANHAMENTO_ATIVIDADES_DESC" name="ACOMPANHAMENTO_ATIVIDADES_DESC"> <?php echo $view_questionario_estagiario->ACOMPANHAMENTO_ATIVIDADES_DESC; ?> </textarea>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">
                <label><strong>8) Você está gostando das atividades que vem desenvolvendo em seu estágio ?</strong></label>
                <br/>
                <?php
                
                    unset($radio1);
                    unset($radio0);
                    
                    if(isset($view_questionario_estagiario->GOSTANDO_ATIVIDADES)){
                        switch ($view_questionario_estagiario->GOSTANDO_ATIVIDADES) {
                            case 1: $radio1 = "checked='true'"; break;
                            case 0: $radio0 = "checked='true'"; break;
                            default: $radio1 = "checked='true'"; break;
                        }
                    } else {
                        $radio1 = "checked='true'";
                    }
                    
                ?>
                <input type="radio" name="GOSTANDO_ATIVIDADES" value="1" <?php echo $radio1; ?>> Sim 
                <input type="radio" name="GOSTANDO_ATIVIDADES" value="0" <?php echo $radio0; ?>> Não
                <br/>
                <strong>Por que?</strong>
            </div>
            <div class="panel-body">
                <textarea class="form-control" id="GOSTANDO_ATIVIDADES_DESC" name="GOSTANDO_ATIVIDADES_DESC"> <?php echo $view_questionario_estagiario->GOSTANDO_ATIVIDADES_DESC; ?> </textarea>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">
                <label><strong>9) Dê "01" à "10", que nota você atribui ao aproveitamento obtido do Estágio ?</strong></label>
                <br/>
                <select class="form-control" name="ATRIBUIR_NOTA">
                    <?php
                
                        if(isset($view_questionario_estagiario->ATRIBUIR_NOTA)){
                            switch ($view_questionario_estagiario->ATRIBUIR_NOTA) {
                                case '1': $option1 = "selected"; break;
                                case '2': $option2 = "selected"; break;
                                case '3': $option3 = "selected"; break;
                                case '4': $option4 = "selected"; break;
                                case '5': $option5 = "selected"; break;
                                case '6': $option6 = "selected"; break;
                                case '7': $option7 = "selected"; break;
                                case '8': $option8 = "selected"; break;
                                case '9': $option9 = "selected"; break;
                                case '10': $option10 = "selected"; break;
                                default: $option1 = "selected"; break;
                            }
                        } else {
                            $option1 = "selected";
                        }

                    ?>
                    <option value="1" <?php echo $option1 ;?>>01</option>
                    <option value="2" <?php echo $option2 ;?>>02</option>
                    <option value="3" <?php echo $option3 ;?>>03</option>
                    <option value="4" <?php echo $option4 ;?>>04</option>
                    <option value="5" <?php echo $option5 ;?>>05</option>
                    <option value="6" <?php echo $option6 ;?>>06</option>
                    <option value="7" <?php echo $option7 ;?>>07</option>
                    <option value="8" <?php echo $option8 ;?>>08</option>
                    <option value="9" <?php echo $option9 ;?>>09</option>
                    <option value="10" <?php echo $option10 ;?>>10</option>
                </select>
                <br/>
                <strong>Por que?</strong>
            </div>
            <div class="panel-body">
                <textarea class="form-control" id="ATRIBUIR_NOTA_DESC" name="ATRIBUIR_NOTA_DESC"> <?php echo $view_questionario_estagiario->GOSTANDO_ATIVIDADES_DESC; ?> </textarea>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">
                <label><strong>10) Você possui alguma dúvida relacionada ao processo de estágio ou Banco de Estágio ?</strong></label>
                <br/>
                <?php
                
                    unset($radio1);
                    unset($radio0);
                    
                    if(isset($view_questionario_estagiario->DUVIDA_ESTAGIO)){
                        switch ($view_questionario_estagiario->DUVIDA_ESTAGIO) {
                            case 1: $radio1 = "checked='true'"; break;
                            case 0: $radio0 = "checked='true'"; break;
                            default: $radio1 = "checked='true'"; break;
                        }
                    } else {
                        $radio1 = "checked='true'";
                    }
                    
                ?>
                <input type="radio" name="DUVIDA_ESTAGIO" value="1" <?php echo $radio1; ?>> Sim 
                <input type="radio" name="DUVIDA_ESTAGIO" value="0" <?php echo $radio0; ?>> Não
                <br/>
                <strong>Se sim quais?</strong>
            </div>
            <div class="panel-body">
                <textarea class="form-control" id="DUVIDA_ESTAGIO_DESC" name="DUVIDA_ESTAGIO_DESC"> <?php echo $view_questionario_estagiario->DUVIDA_ESTAGIO_DESC; ?> </textarea>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">
                <label><strong>11) Se você tem algo para sugerir e/ou criticar ao Banco de Estágio, aproveite o espaço abaixo. Sua opinião é muito importante para aperfeiçoamento de nosso relacionamento, tanto com o estagiário quanto com as Empresas, na busca pelo melhor resultado.</strong></label>
            </div>
            <div class="panel-body">
                <textarea class="form-control" id="CRITICAR_DESC" name="CRITICAR_DESC"> <?php echo $view_questionario_estagiario->CRITICAR_DESC; ?> </textarea>
            </div>
        </div>

        <?php if ($view_papel == "MASTER") { ?>

            <div class="panel panel-default">
                <div class="panel-heading">
                    <label><strong>Espaço para uso da Parceria.</strong></label>
                </div>
                <div class="panel-body">
                    <textarea class="form-control" id="PARCERIA_DESC" name="PARCERIA_DESC"> <?php echo $view_questionario_estagiario->PARCERIA_DESC; ?> </textarea>
                </div>
            </div>

        <?php } ?>

        <hr/>        
        <input type="submit" class="btn btn-primary btn-lg" role="button" value="Enviar"/>
        <hr/>
        <br/>

    </div>
</form>





<?php require_once 'footer.phtml'; ?>